#!/usr/bin/env bash
set -e

print=""
if [ "$1" = "-" ]; then
  print=1
  shift
fi

shell="$1"
if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  cmd_string="eval \"\$(${_SUB_ROOT}/bin/sub init -)\""

  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshenv'
    ;;
  fish )
    profile="~/.config/config.fish"
    # Slightly different message for fish.
    # eval in fish won't cope with the multiline output of this script.
    # But it's source command will eat it all properly.
    cmd_string="${_SUB_ROOT}/bin/sub init - | source"
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load sub automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo $cmd_string
    echo
  } >&2

  exit 1
fi

case "$shell" in 
bash | zsh )
  echo "export PATH=\"\${PATH}:${_SUB_ROOT}/bin\""
  ;;
fish )
  echo "set -x PATH \"\$PATH:${_SUB_ROOT}/bin\""
  ;;
esac

case "$shell" in
bash | zsh | fish )
  echo "source \"$root/completions/sub.${shell}\""
  ;;
esac

commands=(`sub commands --sh`)
IFS="|"
case "$shell" in 
bash | zsh )
cat <<EOS
_sub_wrapper() {
  local command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`sub "sh-\$command" "\$@"\`;;
  *)
    command sub "\$command" "\$@";;
  esac
}
EOS
;;
fish )
cat <<EOFS
function sub 
  set -l command "\$argv[1]"
  if [ (count \$argv) -gt 0 ]
    set -e argv[1]
  end

  switch \$command
    case \$commands
      eval (sub "sh-\$command" "\$argv")
      
    case '*'
      command sub "\$command" "\$argv"
  end
end
EOFS
;;
esac

# zsh can't pass argument with aliases, but bash can.
# zsh can have functions with the name being only numbers, but bash can't.
# fix both cases here by letting zsh have a function, and bash have its alias.
case "$shell" in
bash )
  echo "alias sub=_sub_wrapper"
  ;;
zsh )
  echo "sub=_sub_wrapper"
  ;;
esac
